### ISSUE TITLE
error after running

### ISSUE THREAD

**Issue by pavel06081991** [idefy/gulp-jshint-jenkins-reporter#2]
Here is my gulp task code:

``` javascript
var gulp = require('gulp');
var jshint = require('gulp-jshint');

var config = require('../task.config');

gulp.task('lint', function() {
  return gulp.src(config.scriptsPattern)
    .pipe(jshint('./.jshintrc'))
    .pipe(jshint.reporter('gulp-jshint-jenkins-reporter', {
      filename: 'jenkins-reports/jshint-checkstyle.xml'
    }));
});
```

When I run lint task, I get this error:

Error: No property column in error object
    at Error (native)
    at makeAttribute (D:\work\projects\kron-wfcu\setup-apps\node_modules\gulp-jshint-jenkins-reporter\index.js:86:35)
    at D:\work\projects\kron-wfcu\setup-apps\node_modules\gulp-jshint-jenkins-reporter\index.js:137:13
    at Array.forEach (native)
    at D:\work\projects\kron-wfcu\setup-apps\node_modules\gulp-jshint-jenkins-reporter\index.js:134:15
    at Array.forEach (native)
    at module.exports (D:\work\projects\kron-wfcu\setup-apps\node_modules\gulp-jshint-jenkins-reporter\index.js:131:21)
    at DestroyableTransform.<anonymous> (D:\work\projects\kron-wfcu\setup-apps\node_modules\gulp-jshint\src\reporters\index.js:48:7)
    at DestroyableTransform._transform (D:\work\projects\kron-wfcu\setup-apps\node_modules\gulp-jshint\src\stream.js:34:15)
    at DestroyableTransform.Transform._read (D:\work\projects\kron-wfcu\setup-apps\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:184:10)

If I set level: 'ei', it works normally, if I set level: 'ewi', I get the same error.

With jscs it works without any problem, here is gulp task for jscs which works good in any case:

``` javascript
var gulp = require('gulp-param')(require('gulp'), process.argv);
var jscs = require('gulp-jscs');
var config = require('../task.config');
var stylish = require('gulp-jscs-stylish');
var jshint = require('gulp-jshint');

gulp.task('jsCodeStyle', function() {
  return gulp.src(config.scriptsPattern)
    .pipe(jscs({
      configPath: '.jscs.json'
    }))
    .pipe(stylish.combineWithHintResults())
    .pipe(jshint.reporter('gulp-jshint-jenkins-reporter', {
      filename: 'jenkins-reports/jscs-checkstyle.xml'
    }));
});
```

**Comment by spaceribs** [comment]
Should be fixed by cafbb1256e5e54139972225437f1d566f2d434a8

**Comment by ghost** [comment]
Is this issue still being worked on?
Because i get exactly the same error.
This is the code that i use:

``` javascript
gulp.task('lint', function() {
    return gulp
        .src('master/js/custom/**/*.js')
        .pipe($.jshint())
        .pipe($.jshint.reporter('gulp-checkstyle-jenkins-reporter', {
            filename: 'test_out/jshint-checkstyle.xml',
            level: 'ewi'
        }));
});
```

**Comment by ghost** [comment]
removing the if statement in makeAttribute function seems to work for me but i dont think that is an ideal solution

**Comment by spaceribs** [comment]
@nicosmolders the version number hasn't been updated since this change was implemented, you can grab the master branch directly or wait until @idefy bumps it.
